## Basic Configuration

baseurl = "https://smehta.ca" 
builddrafts = true
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Sameer Mehta"
title = "Sameer Mehta"

theme = "goa"

## Hugo Built-in Features
googleAnalytics = "UA-111641015-2"
enableRobotsTXT = true

## Site Settings
[params]
author = "Sameer Mehta"
intro = "Product Driven Software Engineer"
description = "Interested in Fintech, Data Driven Design, and a whole lot more!"
authorimage = "Sameer.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Sameer Mehta Software Engineer"
keywords = "software,blog,fintech,go,dgraph,graphql,apollo,react,microservices,developer,software engineer"

## Social Accounts
[params.social]
github = "smehtaca"
linkedin = "smehtaca"
email = "sameer@smehta.ca"

## Extras
[params.extra]
copyright = "© 2018. Sameer Mehta." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    weight = 100
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 200
    url = "https://www.github.com/smehtaca"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 300
    url = "/blog/"